name: Auto-merge
on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'Sengolda' }}
    steps:
      - name: Merge
        run: gh pr merge --auto -s "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
